### ISSUE TITLE
Site Protection Not working

### ISSUE THREAD

**Issue by temwa** [elic-dev/laravel-site-protection#10]
Hi,

I have followed the documentation but site protection is not working. I was expecting that every page of the app would not be browsable without a password but nothing happens.

I am on Laravel 5.6

Thanks

**Comment by L1lle** [comment]
Well,
Hard to tell what's wrong. Sounds to me like a misconfiguration. But there are a few things I have to ask:

- Does this package show up after composer install in the autodiscover list?
- Do you have set a value in your `.env` file for `SITE_PROTECTION_PASSWORDS` ?
- Do you use a config cache? Make sure it's cleared.
- Did you add the Middleware to the routes (e.g. `app/Http/Kernel.php` or `routes.php`)?

**Comment by temwa** [comment]
Clearing the config cache worked.

Thank you so much.
