### ISSUE TITLE
array_get() has been changed to data_get() in laravel 6 / Add Laravel 6 Support

### ISSUE THREAD

**Issue by Dopey117** [elic-dev/laravel-site-protection#13]
Just in case anyone is still using this, not sure if its being updated anymore but if you are on laravel 6 you will have to go into /vendor/elic-dev/laravel-site-protection/src/Http/Middleware/SiteProtection.php and update the array_get() to be data_get() on line 35.

I guess you could also install the laravel helpers package as well https://laravel.com/docs/6.x/upgrade#helpers

**Comment by L1lle** [comment]
Thanks. 
I was just thinking about this while testing the new Laravel 6 Version.

I'll have a look into it soon.

**Comment by Dopey117** [comment]
Cool thanks man. I use this plugin all the time its very handy!

**Comment by L1lle** [comment]
I've changed the `array_get` function to the usage of the `Arr::get` namespace. This will support both versions (Laravel 5 and Laravel 6). The `data_get` function has been introduced in documentation 5.5. But this package might be used for older projects as well.

Released with version 1.0.5 .
