### ISSUE TITLE
Add rate limiting

### ISSUE THREAD

**Issue by simonbuehler** [elic-dev/laravel-site-protection#17]
hi,

to avoid a bruteforce attack, where should one set the ratelimiting middleware?

**Comment by L1lle** [comment]
I have not used the rate limit middleware. But as far as I read the documentation, just make sure to load the RateLimiter Middleware before this SitePasswortProtection middleware

However, this package will not support any direct implementation of a rate limit function. The goal is to keep it "simple" and just add a "simple" password field.

If your application is likely to be hit by a bruteforce attack and the information behind the password protection are very sensitive (e.g., more than just a developer version of the website), you should consider a different, and more sophisticated protection.

**Comment by simonbuehler** [comment]
Thanks, will try the right order of the middlewares i guess that helps. Nice package for quick & smaller projects 👍

**Comment by simonbuehler** [comment]
adding it to `$middlewareGroups` like
```php
            'throttle:global',
            \ElicDev\SiteProtection\Http\Middleware\SiteProtection::class,
```

rather than to `$middleware` worked
