### ISSUE TITLE
Views are not being published

### ISSUE THREAD

**Issue by wexford0709** [elic-dev/laravel-site-protection#2]
I used the command 
`php artisan vendor:publish --provider="ElicDev\SiteProtection\SiteProtectionServiceProvider" --tag=views`
and got
Nothing to publish for tag [views].

Also, the readme says:
You can make the changes in resources/vendor/views/site-protection/site-protection-form.blade.php.
I think the path should be resources/views/vendor/...

**Comment by L1lle** [comment]
@wexford0709 thanks. This functionality has just been merged into the master branch a couple of minutes ago. What you see is the updated readme file from the master branch but it hasn't been released for composer.

It's now pushed to composer as version 1.0.1, so if you do a `composer update elic-dev/laravel-site-protection` and rerun your command it should be fine.
