### ISSUE TITLE
How to disable site protection

### ISSUE THREAD

**Issue by temwa** [elic-dev/laravel-site-protection#9]
Going through your documentation, I do not see an option to disable site protection.

Please advise.

Thanks

**Comment by L1lle** [comment]
Hi @temwa ,

You can disable it by not setting a password in your `.env` file for `SITE_PROTECTION_PASSWORDS`. 

I'll adjust the readme.md file . 

The common approach is to set a password in your .env file only on develop, staging or preview versions. Your production site does not have a password.

**Comment by temwa** [comment]
@L1lle , Thank you
